### PR TITLE
Pacman support implemented ~

### PR DESCRIPTION
**Pull request by mitki**

### CODE REVIEW

**Comment by ItsSohma** [comment]
What is this?

**Comment by brodycas3** [comment]
A Linux thing

**Comment by mitki** [comment]
The build script is only compatible with Debian based distros at this moment, since it depends on apt-get to install the dependences. Now the script checks if pacman (Arch Linux, Manjaro, Antegos, Parabola) is installed before installing dependences, then it chooses the right package manager.

**Comment by mitki** [comment]
It would be simple to add dnf (Fedora) support as well, but I don't have a Fedora VM atm so I can't double-check the dependences.

e.g.
```bash
elif type dnf > /dev/null 2>&1
then
sudo dnf install "qt5-qtbase-devel" "qt5-qtdeclarative-devel" "qt5-qtscript-devel" "qt5-qtmultimedia-devel" "libpulse-devel" "qt5-qttools-devel"
```

**Comment by Bionus** [comment]
Except for the inconsistent use of sudo, LGTM, thanks :+1:

**Pull request merged**
