### PR TITLE
Added a missing include to fix compilation on Arch

### PR DESCRIPTION
**Pull request by daffy1234**
The compilation kept failing, including the AUR imgbrd-grabber-git package. This fixes it.

### CODE REVIEW

**Comment by daffy1234** [comment]
This fixes issue #1993

**Comment by Bionus** [comment]
LGTM, merged! :+1:

**Comment by FichteFoll** [comment]
This was pushed onto `master` instead of `develop`, where development used to take place. May need a rebase/cherry-picking?

**Comment by Bionus** [comment]
Yes, it's planned, I'll push this tonight

**Pull request merged**
