### PR TITLE
Add rule34.us site format

### LINKED ISSUE #2205: add support for Rule34.us
**Is your feature request related to a problem? Please describe**

No

**Describe the solution you'd like**

I would like for Rule34.us, to be added to Supported sites.

### PR DESCRIPTION
**Pull request by GiovanH**
Resolves #2205

### CODE REVIEW

**Comment by Bionus** [comment]
LGTM at first sight, although you should be posting the `model.ts` file rather than the JS one (and the "check" method also matches normal Gelbooru instances).
I guess using the original Gelbooru (0.1) model was not possible because the URL are different?

**Comment by GiovanH** [comment]
> LGTM at first sight, although you should be posting the `model.ts` file rather than the JS one (and the "check" method also matches normal Gelbooru instances). I guess using the original Gelbooru (0.1) model was not possible because the URL are different?

Yeah, the internal URL schema is different, but the various interfaces exposed there are the same as 0.1. 

also, whoops, i wrote it in javascript. is that supposed to be ts that gets compiled down to js later?

**Comment by GiovanH** [comment]
Should be good now

**Comment by Bionus** [comment]
LGTM 👍

**Pull request merged**
