### PR TITLE
Commit compile_for_mac.sh

### PR DESCRIPTION
**Pull request by yennixsg**
I wrote this script to make the work of compiling imgbrd-grabber on mac
easier to do and wanted to share it back to the project. Hopefully it's something you fine folks feel would be helpful.

The script itself takes out a lot of the manual labor found in the compile doc:
	https://github.com/Bionus/imgbrd-grabber/wiki/Compilation#macos

Instead, it attempts to do the following, covering off as many prereqs
and bases as I could think:

1) If HomeBrew isn't installed, run the ruby script to install it
2) Install prerequisites
	cmake,
	gcc,
	qt5
    NOTE: The default qt5 does not have mysql libs compiled into it.
    If you need mysql, dialogues allow you to trigger brew into
    doing a full build of Qt...after a warning that this can take up to
    an hour or more to complete just on it's own.

3) It also installs a script dependency: jq(1). It's a light-weight
commandline json parsing utility, and is used to parse Brew package
information cleanly.

4) Since imgbrd-grabber needs https, and build depends on openssl libs,
this script checks to see if any version of openssl has been installed
with brew, and if not it also pulls in a bottled version with brew that
		//shouldn't//
clobber other openssl environments on the machine. I dont think it will
at least.

5) With all those prerequisites out of the way, it does a git pull to
update the gir repository.

If the script is not actually WITH the git repository, the script clones
the repo from github into the location the script was executed from.

6) After that, the script finally starts doing the compile, mostly
according to the instructions at wiki/Compilation#macos

cmake has dependencies for OpenSSL though, so the script hooks it into
the bottle it downloaded or any other preexisting brew-installed openssl
libs it found before.

7) One difference the script does however is sort and move finished assets
around into a mac .app folder so it can be run from the GUI.

8) Next to last is the script checks if there's a previous install of
imgbrd-grabber at ${HOME}/Applications/Grabber.app

If there IS an old version there, and the user says ok, then it starts
pulling user configuration data out of

	${HOME}/Applications/Grabber.app/Contents/MacOS
		/*.txt
		/*.ini
		/*.log
		/*.igl
		/thumbs/

and putting it all into the new build.

9) Finally the script lets the user put the new application into
${HOME}/Applications and launch it, with the preserved session from the
old app intact.

One of the things the script does not do is install any of the xcode/git fundamental packages. I just didn't want to get that deep into the weeds where the script is provisioning an entire end-to-end build environment all in one shot;) I figure brew through gcc to app is enough to help smooth the way for most techie mac users out there.

### CODE REVIEW

**Comment by Bionus** [comment]
Hello!

Sorry for not answering earlier, I'm out of internet, and for still 2 weeks!
After a quick look however, your review looks good, I can see it must have taken a while to do it, so thanks! 👍

Just a few remarks before I go internet-less again:
- Shouldn't it overwrite `build-mac.sh` though, instead of creating a new file?
- Is the last line `# vim:ts=4:sw=4...` supposed to be there?

I'll merge it when I come back home and can take a better look 😄

**Comment by yennixsg** [comment]
Hi back!:D

> Shouldn't it overwrite build-mac.sh though, instead of creating a new file?

Technically, yes it should depreciate that file. I didn't overwrite it because...it seemed rude to blatantly obliterate the original. 

That's a silly answer, and I can re-name to build-mac.sh and re-commit the pull request if you'd prefer!

> Is the last line `# vim:ts=4:sw=4...` supposed to be there?

That's a Vim style comment called a [modeline](http://vim.wikia.com/wiki/Modeline_magic)
It's cosmetic and can be removed, but it will do the following if the script is viewed within vim: 

```
ts=4 - Sets TabStop to 4, which replaces tab chars with 4 space chars if 'expandtab' is enabled

sw=4 - Sets ShiftWidth to number of space characters inserted for indentation

tw=0 - Sets TextWidth to 0, disabling the word-wrapping at 80 columns

noexpandtab - Disables conversion of tabs to spaces (despite the ts=4 value)

autoindent - copies the indentation from the previous line, when starting a new line

foldmethod=marker - Tells Vim to fold text when it finds a {{{X marker

foldcolumn=4 - Prints a 4-column wide 'graph' of fold depth
```

**Comment by Bionus** [comment]
LGTM!

Thanks for the script, I guess most MacOS users will find it easier to use an interactive install script rather than debugging some obscure build failures :smile:

**Comment by yennixsg** [comment]
That's my hope too! I hope it helps and thank you for a really stupendous app dude!

**Pull request merged**
