### PR TITLE
Update log-tab.ui

### PR DESCRIPTION
**Pull request by ProtagNeptune**
https://github.com/Bionus/imgbrd-grabber/issues/3218

### CODE REVIEW

**Comment by ProtagNeptune** [comment]
Oops...sorry for the commits spam? 😅

**Review by Bionus — CHANGES_REQUESTED** [review]
LGTM for the UI file, but did you update the `.ts` files by hand? 😅 

There's a CMake command for that, that'd be not only easier but it'd avoid having incorrect translations like now in Russian for example:
```xml
<source>Open log folder</source>
<translation>Открыть каталог настроек</translation>
```
The old one should be marked as missing and a new one created AFAIK. I'll run the command on your PR 👍

**Comment by ProtagNeptune** [comment]
> LGTM for the UI file, but did you update the `.ts` files by hand? 😅

Yeah, I changed those files before finding out about the codespace thing so I did it one by one...

> There's a CMake command for that, that'd be not only easier but it'd avoid having incorrect translations like now in Russian for example:
> 
> ```
> <source>Open log folder</source>
> <translation>Открыть каталог настроек</translation>
> ```
> 
> The old one should be marked as missing and a new one created AFAIK. I'll run the command on your PR 👍

Sorry about that. Should it be something like that now:
```
<source>Open log folder</source>
<translation type="unfinished"/>
 ```

**Comment by Bionus** [comment]
FWIW, the easiest way to update those files in a correct way is to build the `translations` (all projects) or `General_translations` (gui only) target. Then, Qt will automatically look for new translations and missing ones, and update the files accordingly. Just did it on your PR, in the end it didn't make much difference except for the missing "vanished" translations 😄

**Review by Bionus — APPROVED** [review]
LGTM! 👍

**Pull request merged**
