### PR TITLE
Fixes built-in log viewer

### PR DESCRIPTION
**Pull request by Flat**

### CODE REVIEW

**Comment by Bionus** [comment]
How is it performance-wise?

The main reason I removed the log viewer (on purpose long time ago) was because it was crazily slow to display and also slowed down the program as a whole (which was not worth the price of showing a text box).

**Comment by Flat** [comment]
I don't encounter any noticeable slowdowns on Linux. (Although if the log file is allowed to grow I can see there being some memory issues as it loads the whole file, this can be changed to only load X amount of lines though). This shouldn't introduce too much overhead as it just watches the log file for changes and if it's changed reads the file into the list.

**Comment by Bionus** [comment]
I just tried it out on Windows. There was no slowdown, but when I started a big batch download to make sure (they generate a lot of log messages), they didn't show up in the log tab for some reason, despite the file being written to. I'll check what might be the reason on Windows.

Actually, I don't know if it's necessary to watch the file, since the `_log` global is always up-to-date? (could be read instead of re-loading the file maybe?)

**Comment by Bionus** [comment]
Ok, by checking Qt Creator's source code, that also has a log viewer, it seems the performance problem was mainly due to the usage of a QLabel. I'll merge this all into develop, thanks! :smile:

**Pull request merged**
