### PR TITLE
Trim whitespace

### PR DESCRIPTION
**Pull request by ItsSohma**
The only file that I left whitespace on was `words.txt` because I thought the whitespace at the end of the file may serve a purpose. Otherwise, I just opened all of the files and saved them in my code editor and it stripped the trailing whitespace off of every line.

### CODE REVIEW

**Comment by Bionus** [comment]
Thanks! :+1:
I try to not add any trailing whitespace but sometimes a few slip my watch.

A remark on the review though: you shouldn't change the contents of the files in `tests/resources/pages/`. They are used for tests and must be direct unmodified copies of the websites' pages.

> The only file that I left whitespace on was words.txt because I thought the whitespace at the end of the file may serve a purpose

They don't, they even add a small CPU overhead. :smile:

**Comment by ItsSohma** [comment]
Despite it failing to build, I assume that is due to the branch not currently building. This commit should not effect the build at all.

**Comment by Bionus** [comment]
Yes, it's just the tests crashing at the end for some reason on the Travis Linux VM (after all passing).

**Comment by ItsSohma** [comment]
Updated

**Pull request merged**
