### PR TITLE
Fix #546

### LINKED ISSUE #546: Broken QsciScintilla on Ubuntu
I was affected by the segfault builds on my Linux Mint 17.3 system. Commit a3856511072a6cf8b5073300054250b39803bc8a fixed that (thanks btw!), but I still can't compile the latest source due to references to missing QsciScintilla parts.

```
g++ -m64 -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu -o Grabber aboutwindow.o addgroupwindow.o adduniquewindow.o batchwindow.o blacklistfix.o blacklistfix2.o commands.o conditionwindow.o crashhandler.o customwindow.o detailswindow.o downloader.o emptydirsfix.o emptydirsfix2.o favorite.o favoritestab.o favoritewindow.o filenamewindow.o functions.o image.o imagethread.o json.o main.o mainwindow.o md5fix.o optionswindow.o page.o pool.o pooltab.o QAffiche.o QBouton.o qclosabletabwidget.o searchtab.o searchwindow.o site.o sitewindow.o sourcessettingswindow.o sourceswindow.o startwindow.o tag.o tagtab.o textedit.o zoomwindow.o qcommandlineoption.o qcommandlineparser.o rename-existing-1.o rename-existing-2.o qrc_resources.o moc_aboutwindow.o moc_addgroupwindow.o moc_adduniquewindow.o moc_batchwindow.o moc_blacklistfix.o moc_blacklistfix2.o moc_conditionwindow.o moc_customwindow.o moc_detailswindow.o moc_downloader.o moc_emptydirsfix.o moc_emptydirsfix2.o moc_favoritestab.o moc_favoritewindow.o moc_filenamewindow.o moc_image.o moc_imagethread.o moc_mainwindow.o moc_md5fix.o moc_optionswindow.o moc_page.o moc_pooltab.o moc_QAffiche.o moc_QBouton.o moc_searchtab.o moc_searchwindow.o moc_site.o moc_sitewindow.o moc_sourcessettingswindow.o moc_sourceswindow.o moc_startwindow.o moc_tagtab.o moc_textedit.o moc_zoomwindow.o moc_rename-existing-1.o moc_rename-existing-2.o   -L/usr/X11R6/lib64 -lQt5MultimediaWidgets -L/usr/lib/x86_64-linux-gnu -lQt5Multimedia -lQt5Widgets -lQt5Script -lQt5Sql -lQt5Xml -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
filenamewindow.o: In function `FilenameWindow::FilenameWindow(QString, QWidget*)':
filenamewindow.cpp:(.text+0x14f): undefined reference to `QsciScintilla::QsciScintilla(QWidget*)'
filenamewindow.cpp:(.text+0x16b): undefined reference to `QsciLexerJavaScript::QsciLexerJavaScript(QObject*)'
filenamewindow.o: In function `FilenameWindow::format()':
filenamewindow.cpp:(.text+0x1b0a): undefined reference to `QsciScintilla::text() const'
collect2: error: ld returned 1 exit status
make[1]: *** [Grabber] Error 1
```

I have libqscintilla2-dev and libqt5scintilla2-dev installed.

### PR DESCRIPTION
**Pull request by Flat**

### CODE REVIEW

**Comment by Bionus** [comment]
The problem is that the lib could also be in `/usr/lib64` (that's where it is on my VM).

I believe just using `lqscintilla2` if the two previous exists() didn't succeed would be the best option here? Since even the FHS can't prevent all problems.

**Comment by Flat** [comment]
While I agree it's good to have a catch all, you would still get segfaults if you use lqscintilla2 because it's the wrong library on linux. in the case of ubuntu/fedora it's called lqt5scintilla2 on arch linux it's lqscintilla2-qt5. I'm not sure about other distros.

**Comment by Bionus** [comment]
Then maybe disable Qscintilla if none of the 3 (4 including lib64) files are found? (by removing the `define` and printing some error message)
Since it won't compile otherwise, and that lib isn't really critical.

Thanks for all the PR btw, it really helps :smile:

**Comment by Flat** [comment]
I think something like this works fairly well? More of what you were thinking of? And no problem. I like the program and bugs aren't fun to fix by yourself!

**Comment by Bionus** [comment]
Yeah I think like this it will cover all use cases while still preventing using an invalid lib and segfaulting!

**Pull request merged**
