### PR TITLE
Added post filter for aspect ratio

### PR DESCRIPTION
**Pull request by Gnathonic**
Aspect ratio is calculated from height and width.
Supports ranges.
Has autocomplete suggestions for portrait, landscape, and a squarish range (mostly to demonstrate usage for anyone who types in "aspect_ratio")
aspect_ratio can be used in filename generation.

### CODE REVIEW

**Comment by Bionus** [comment]
LGTM!
Any reason you didn't follow the [same syntax as Danbooru](https://danbooru.donmai.us/wiki_pages/help:cheatsheet) (for consistency as other filters try to do), i.e. `ratio:4:3` and similar?

I just started the tests and will merge once they're green 👍 
Seems like it's not passing the uncrustify check though.

**Comment by Gnathonic** [comment]
Mostly just cause I didn't think of it at first. When you calculate a aspect ratio it's a decimal, and I didn't think about adding factional support until later. Decimal is a common enough, and well enough understood format. It's usable as is. That said I did plan to come back this weekend and add fractional support. C++ isn't a language I use often, so parsing what's here and writing clean code has been slow, but still fun

**Comment by Gnathonic** [comment]
My original plan was to use "aspect" since "aspect_ratio" was already being used by one of the boorus, but decided that would have just made things more confusing for the user. I didn't know that "ratio" was a filter supported by some boorus. I'll close this for now and come back with "ratio" and support for fractional aspect ratios.

**Comment by Oleksandrigo** [comment]
I think a thing like that would be very helpful. Not every site has its own filters like ratio. And even if they do, they are not always really that ratio. It would be cool if grabber could analyze the resolution of the picture and make a conclusion it is suitable for a particular resolution or not.

**Comment by Oleksandrigo** [comment]
My original plan was to use "aspect" since "aspect_ratio" was already being used by one of the boorus, but decided that would have just made things more confusing for the user. I didn't know that "ratio" was a filter supported by some boorus. I'll close this for now and come back with "ratio" and support for fractional aspect ratios.

**Comment by Oleksandrigo** [comment]
I think a thing like that would be very helpful. Not every site has its own filters like ratio. And even if they do, they are not always really that ratio. It would be cool if grabber could analyze the resolution of the picture and make a conclusion it is suitable for a particular resolution or not.

**Pull request closed without merging**
